backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "auta"
    label: "Oferty Aut"
    folder: "content/auta"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Marka i Model", name: "title", widget: "string"}
      - {label: "Zdjęcie główne (na listę)", name: "image", widget: "image"}
      - {label: "Galeria zdjęć (szczegóły)", name: "gallery", widget: "list", field: {label: "Zdjęcie", name: "img", widget: "image"}}
      - {label: "Cena", name: "price", widget: "string"}
      - {label: "Rok produkcji", name: "year", widget: "string"}
      - {label: "Silnik", name: "engine", widget: "string"}
      - {label: "Przebieg", name: "mileage", widget: "string"}
      - {label: "Skrzynia biegów", name: "gearbox", widget: "string"}
      - {label: "Napęd", name: "drive", widget: "string"}
      - {label: "Status", name: "status", widget: "select", options: ["Dostępny", "W transporcie", "Zarezerwowany", "Sprzedany"]}
      - {label: "Opis pojazdu", name: "body", widget: "markdown"}