backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "auta"
    label: "Oferty Aut"
    folder: "content/auta"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł (Marka i Model)", name: "title", widget: "string"}
      - {label: "Cena", name: "price", widget: "string"}
      - {label: "Silnik/Moc", name: "engine", widget: "string"}
      - {label: "Status (Dostępny/Rezerwacja)", name: "status", widget: "select", options: ["Dostępny", "Zarezerwowany", "Sprzedany"]}
      - {label: "Zdjęcie główne", name: "image", widget: "image"}
      - {label: "Opis", name: "body", widget: "markdown"}